import { Injectable, HttpException, HttpStatus } from '@nestjs/common';
import { GoogleGenAI } from '@google/genai';

@Injectable()
export class AiService {
  private ai: GoogleGenAI;

  constructor() {
    // Make sure to set GEMINI_API_KEY in the environment
    this.ai = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY || 'dummy-key',
    });
  }

  private async withRetry<T>(
    operation: () => Promise<T>,
    maxRetries = 5,
    baseDelayMs = 1000,
  ): Promise<T> {
    let attempt = 0;
    while (true) {
      try {
        return await operation();
      } catch (err) {
        attempt++;
        const e = err as { status?: number; message?: string };
        const isTransient =
          e.status === 503 ||
          e.message?.includes('503') ||
          e.status === 429 ||
          e.message?.includes('429') ||
          e.message?.includes('JSON_PARSE_ERROR');

        if (isTransient && attempt < maxRetries) {
          console.warn(`Transient error/Parse error encountered (attempt ${attempt}/${maxRetries}): ${e.message}. Retrying...`);
          const delay = baseDelayMs * Math.pow(2, attempt - 1);
          await new Promise((resolve) => setTimeout(resolve, delay));
          continue;
        }

        console.error('AI Generation Error:', e.message);
        throw new HttpException(
          'The AI assistant is temporarily unavailable or failed to process the request. Please try again later.',
          HttpStatus.INTERNAL_SERVER_ERROR,
        );
      }
    }
  }

  async generateJson(prompt: string, systemInstruction: string): Promise<any> {
    return this.withRetry(async () => {
      const response = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: {
          systemInstruction: systemInstruction,
          responseMimeType: 'application/json',
        },
      });
      const rawText = response.text || '{}';
      try {
        // Remove possible markdown formatting generated by the model
        let cleanedText = rawText.replace(/```(?:json)?\n?/g, '').replace(/```\n?/g, '').trim();
        
        // Import jsonrepair dynamically or at top level, but for simplicity here we can just require it if we didn't import at top
        const { jsonrepair } = require('jsonrepair');
        
        return JSON.parse(jsonrepair(cleanedText));
      } catch (err) {
        console.error('JSON Parse Error in generateJson. Raw text:', rawText);
        throw new Error(`JSON_PARSE_ERROR: ${(err as Error).message}`);
      }
    });
  }

  async generateText(
    prompt: string,
    systemInstruction: string,
  ): Promise<string> {
    return this.withRetry(async () => {
      const response = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: {
          systemInstruction: systemInstruction,
        },
      });
      return response.text || '';
    });
  }
}
